package contract

const (
	APIVersion     = 1
	StorageVersion = 1
)

type Flag struct {
	Name        string `json:"name"`
	Kind        string `json:"kind"`
	Description string `json:"description"`
}
type Command struct {
	Name     string   `json:"name"`
	Summary  string   `json:"summary"`
	Options  []Flag   `json:"options"`
	Examples []string `json:"examples"`
}

var Commands = []Command{
	{Name: "init", Summary: "Initialize a ticket repository at ./tickets, TICKET_REPOSITORY, or the selected scope root.", Examples: []string{"ticket init"}},
	{Name: "create", Summary: "Create a new ticket.", Options: []Flag{{"TITLE [OBJECTIVE] (positional)", "string", "Ticket title and optional objective."}, {"-t, --title", "string", "Ticket title."}, {"-p, --priority", "int", "0-4, default 2."}, {"--tag", "string (repeatable)", "Lowercase tag token."}, {"--parent", "id", "Parent ticket ID."}, {"--depends-on", "id (repeatable)", "Prerequisite ticket ID."}, {"--input", "-", "Read a JSON object with create fields from stdin."}, {"-e, --edit", "bool", "Open the new ticket in the editor; with no title, use a starter template."}}, Examples: []string{"ticket create \"Fix login\" \"Make login reliable\"", "ticket create \"Paste objective\" -", "ticket create -t \"Fix login\" -p 1", "ticket create -e", "ticket create --input -"}},
	{Name: "delete", Summary: "Permanently delete tickets.", Options: []Flag{{"ID... (positional)", "id", "Full or unambiguous ticket IDs separated by spaces or commas."}}, Examples: []string{"ticket delete 20260913-00001", "ticket delete 20260913-00001,20260913-00002"}},
	{Name: "bump", Summary: "Raise a ticket's priority by one level.", Options: []Flag{{"ID (positional)", "id", "Full or unambiguous shorthand ticket ID."}}, Examples: []string{"ticket bump 20260913-00001"}},
	{Name: "list", Summary: "List tickets (human default: all nonterminal; JSON default: open).", Options: []Flag{{"STATE... or ID... (positional)", "state|id", "Ticket states or ID prefixes."}, {"-s, --state", "enum (repeatable)", "Select one or more ticket states."}, {"-a, --all", "bool", "Include completed and rejected tickets."}, {"-l, --long", "bool", "Accepted compatibility alias for the expanded list form."}, {"-t, --by-id", "bool", "Sort by descending ticket ID."}, {"-u, --by-modified", "bool", "Sort by most recently modified."}, {"--tag", "string (repeatable)", "All listed tags must be present."}, {"--without-tag", "string (repeatable)", "None of the listed tags may be present."}, {"--assignee", "token", "Exact assignee match."}, {"--unassigned", "bool", "No assignee."}, {"--parent", "id", "Exact parent match."}, {"--priority", "int", "Exact priority match."}, {"--limit", "int", "Positive result limit, default 20 unless bare human list or human all view is used."}, {"--offset", "int", "Skip this many sorted results before applying --limit."}, {"--fields", "csv", "Projection; id mandatory."}, {"--markdown", "bool", "Use Markdown table output."}}, Examples: []string{"ticket list --tag billing --limit 50", "ticket list open hold", "ticket list 20260913-00001", "ticket list --state open --state hold", "ticket ls -a", "ticket ls -lt", "ticket ls -ltu"}},
	{Name: "grep", Summary: "Find tickets by matching ID or complete TASK.md content.", Options: []Flag{{"EXPRESSION... (positional)", "string|regexp", "Every substring or regular expression must match ticket ID or content."}}, Examples: []string{"ticket grep parser", "ticket grep parser retry", "ticket grep '^20260913-'", "ticket grep '^# Fix'"}},
	{Name: "ready", Summary: "List actionable unassigned tickets.", Options: []Flag{{"--tag", "string (repeatable)", "All listed tags must be present."}, {"--without-tag", "string (repeatable)", "None of the listed tags may be present."}, {"--parent", "id", "Exact parent match."}, {"--priority", "int", "Exact priority match."}, {"--limit", "int", "Positive result limit, default 20."}, {"--fields", "csv", "Projection; id mandatory."}, {"--markdown", "bool", "Use Markdown table output."}}, Examples: []string{"ticket ready --tag billing"}},
	{Name: "next", Summary: "Select the first ticket from the open or review queue, optionally claiming it.", Options: []Flag{{"[open|review] (positional)", "queue", "Select implementation or review work; open is the default."}, {"--tag", "string (repeatable)", "Require every tag."}, {"--priority", "int", "Exact priority filter, 0-4."}, {"--claim", "bool", "Claim the selected ticket for --actor or TICKET_ACTOR."}, {"--markdown", "bool", "Use Markdown table output."}}, Examples: []string{"ticket next", "ticket next review --claim -j", "ticket next --tag backend --claim -j"}},
	{Name: "wait", Summary: "Wait for open or review work, optionally claiming it.", Options: []Flag{{"[open|review] (positional)", "queue", "Select implementation or review work; open is the default."}, {"--tag", "string (repeatable)", "Require every tag."}, {"--priority", "int", "Exact priority filter, 0-4."}, {"--claim", "bool", "Resume this actor's matching work or claim available work."}}, Examples: []string{"ticket wait --claim -j", "ticket wait review --claim -j", "ticket wait --tag windows --claim -j"}},
	{Name: "show", Summary: "Show one ticket (default sections: objective, acceptance, handoff, work log).", Options: []Flag{{"ID (positional)", "id", "Full or unambiguous shorthand ticket ID."}, {"--section", "key (repeatable)", "Known section key; replaces the default selection."}, {"--full", "bool", "Entire Markdown body after metadata."}, {"--max-bytes", "int", "Budget 1-1048576 for returned text."}, {"--readiness", "bool", "Include readiness and blocker computation."}, {"--markdown", "bool", "Use Markdown output."}}, Examples: []string{"ticket show", "ticket show 20260913-00001 --readiness", "ticket show 20260913-00001 --full"}},
	{Name: "edit", Summary: "Open a ticket in the configured editor.", Options: []Flag{{"ID (positional)", "id", "Full or unambiguous shorthand ticket ID."}}, Examples: []string{"ticket edit"}},
	{Name: "submit", Summary: "Submit an open ticket for independent review.", Options: []Flag{{"ID (positional)", "id", "Full or unambiguous shorthand ticket ID."}, {"--handoff", "string", "Replace Handoff text."}, {"-m, --message", "string", "Append an entry to Work log."}}, Examples: []string{"ticket submit -m \"Ready for review\"", "ticket submit 20260913-00001 -m \"Ready for review\" -j"}},
	{Name: "hold", Summary: "Put an open ticket on hold.", Options: []Flag{{"ID (positional)", "id", "Full or unambiguous shorthand ticket ID."}, {"--handoff", "string", "Replace Handoff text."}, {"-m, --message", "string", "Append an entry to Work log."}}, Examples: []string{"ticket hold 20260913-00001 -m \"Waiting for the API contract\""}},
	{Name: "review", Summary: "Send a ticket to review.", Options: []Flag{{"ID (positional)", "id", "Full or unambiguous shorthand ticket ID; omitted ID uses the current ticket."}, {"-m, --message", "string", "Append an entry to Work log."}}, Examples: []string{"ticket review 20260913-00001", "ticket review -m \"Ready for review\""}},
	{Name: "open", Summary: "Open a ticket for implementation.", Options: []Flag{{"[ID] [HANDOFF] (positional)", "id|string", "Optional ticket ID and positional Handoff text; omitted ID uses the current ticket."}, {"--handoff", "string", "Replace Handoff text."}, {"-m, --message", "string", "Append an entry to Work log."}, {"--claim", "bool", "Claim the opened ticket for --actor or TICKET_ACTOR."}}, Examples: []string{"ticket open 20260913-00001 -m \"Continue implementation\"", "ticket open 20260913-00001 --claim", "ticket open \"Continue implementation\""}},
	{Name: "state", Summary: "Force a lifecycle state.", Options: []Flag{{"ID STATE (positional)", "id state", "Full canonical ticket ID and one of the valid lifecycle states."}, {"-m, --message", "string", "Append an entry to Work log."}}, Examples: []string{"ticket state 20260913-00001 review", "ticket state 20260913-00001 rejected -m \"Administrative correction\""}},
	{Name: "status", Summary: "Show concise operational status for one ticket.", Options: []Flag{{"ID (positional)", "id", "Full or unambiguous shorthand ticket ID."}, {"--markdown", "bool", "Use Markdown output."}}, Examples: []string{"ticket status 20260913-00001", "ticket status 20260913-00001 -j"}},
	{Name: "path", Summary: "Resolve a ticket ID to its TASK.md path.", Options: []Flag{{"ID (positional)", "id", "Full or unambiguous shorthand ticket ID."}, {"--absolute", "bool", "Absolute filesystem path instead of ticket-root-relative."}}, Examples: []string{"ticket path 20260913-00001", "ticket path 20260913-00001 --absolute"}},
	{Name: "update", Summary: "Update fields and/or replace whole sections.", Options: []Flag{{"ID (positional)", "id", "Full or unambiguous shorthand ticket ID."}, {"--tag", "string (repeatable)", "Replace tags; every tag must be unique."}, {"--input", "-", "Read a JSON object with set and/or sections from stdin."}}, Examples: []string{"ticket update 20260913-00001 --tag windows --tag networking", "ticket update 20260913-00001 --input -"}},
	{Name: "claim", Summary: "Claim an actionable unassigned ticket.", Options: []Flag{{"ID (positional)", "id", "Full or unambiguous shorthand ticket ID."}}, Examples: []string{"ticket claim 20260913-00001"}},
	{Name: "release", Summary: "Release ticket ownership.", Options: []Flag{{"ID (positional)", "id", "Full or unambiguous shorthand ticket ID."}, {"--handoff", "string", "Replace Handoff text."}, {"-m, --message", "string", "Append an entry to Work log."}, {"--input", "-", "Read a JSON object with release fields from stdin."}}, Examples: []string{"ticket release 20260913-00001"}},
	{Name: "close", Summary: "Close one or more tickets as completed.", Options: []Flag{{"ID... or STATE... (positional)", "id|state", "Ticket IDs or nonterminal states separated by spaces or commas; all, *, or -a closes every nonterminal ticket."}, {"-s, --state", "state (repeatable)", "Select nonterminal tickets by state."}, {"--outcome", "string", "Optional outcome text."}, {"-m, --message", "string", "Append an entry to Work log."}, {"--input", "-", "Read a JSON object with optional outcome/message fields from stdin."}, {"-a, --all", "bool", "Close every nonterminal ticket."}}, Examples: []string{"ticket close", "ticket close 20260913-00001 -m \"Accepted after review\"", "ticket close open hold", "ticket close -s open -s review"}},
	{Name: "approve", Summary: "Approve review tickets for human signoff.", Options: []Flag{{"ID... or STATE... (positional)", "id|state|all", "Review ticket IDs, or review state; all selects every review ticket."}, {"-s, --state", "state (repeatable)", "Select review tickets by state; review is accepted."}, {"-m, --message", "string", "Append an entry to Work log."}}, Examples: []string{"ticket approve", "ticket approve 20260913-00001 -m \"Reviewed and approved\"", "ticket approve review", "ticket approve all"}},
	{Name: "reject", Summary: "Reject a nonterminal ticket with an outcome.", Options: []Flag{{"[ID] [OUTCOME] (positional)", "id|string", "Optional ticket ID and rejection outcome; omitted ID uses the current ticket."}, {"--outcome", "string", "Nonempty rejection outcome (required unless supplied positionally)."}, {"-m, --message", "string", "Append an entry to Work log."}, {"--input", "-", "Read a JSON object with outcome/message fields from stdin."}}, Examples: []string{"ticket reject 20260913-00001 \"No longer needed\" -m \"Closing after review\"", "ticket reject \"No longer needed\""}},
	{Name: "check", Summary: "Validate ticket metadata and relationship graphs.", Examples: []string{"ticket check"}},
	{Name: "actor", Summary: "Show the effective actor identity.", Examples: []string{"ticket actor", "ticket actor -j"}},
	{Name: "version", Summary: "Report version, API version, and storage version.", Examples: []string{"ticket version"}},
	{Name: "help", Summary: "Show help for one command, or list commands.", Options: []Flag{{"COMMAND (positional)", "command", "Command to describe."}}, Examples: []string{"ticket help", "ticket help create"}},
}
