package contract

const (
	APIVersion     = 2
	StorageVersion = 1
)

type Flag struct {
	Name        string `json:"name"`
	Kind        string `json:"kind"`
	Description string `json:"description"`
}
type Command struct {
	Name     string   `json:"name"`
	Summary  string   `json:"summary"`
	Options  []Flag   `json:"options"`
	Examples []string `json:"examples"`
}

var Commands = []Command{
	{Name: "init", Summary: "Initialize a ticket repository at ./tickets, TICKET_REPOSITORY, or the selected scope root.", Examples: []string{"ticket init"}},
	{Name: "create", Summary: "Create a new ticket.", Options: []Flag{{"TITLE [OBJECTIVE|-] (positional)", "string", "Ticket title and optional forgiving Objective text; a trailing - reads invocation input; human titles may end with #tag tokens."}, {"-t, --title", "string", "Ticket title; human trailing #tag tokens become tags."}, {"-o, --objective", "FILE|-", "Read forgiving Objective Markdown from FILE|-."}, {"--import", "file", "Read a complete strict Ticket Markdown document from a file or stdin with -."}, {"-p, --priority", "int", "0-4, default 2."}, {"--tag", "string (repeatable)", "Lowercase tag token."}, {"--parent", "id", "Parent ticket ID."}, {"--depends-on", "id (repeatable)", "Prerequisite ticket ID."}, {"--input", "file", "Read a strict JSON object with create fields from a file or stdin with -."}, {"-e, --edit", "bool", "Open the new ticket in the editor; with no title, use a starter template."}}, Examples: []string{"ticket create \"Fix login #auth\" --tag urgent", "ticket create \"Fix login\" \"Objective text\"", "ticket create \"Fix login\" -", "ticket create --objective /tmp/objective.md", "ticket create --import /tmp/full-ticket.md", "ticket create --input -"}},
	{Name: "delete", Summary: "Permanently delete tickets.", Options: []Flag{{"ID... (positional)", "id", "Full or unambiguous ticket IDs separated by spaces or commas."}}, Examples: []string{"ticket delete 20260913-00001", "ticket delete 20260913-00001,20260913-00002"}},
	{Name: "archive", Summary: "Move unassigned terminal tickets into the visible archive.", Options: []Flag{{"ID or TQL... (positional)", "id|query", "Ticket ID or shell-friendly TQL over active tickets."}, {"-q, --query", "TQL...", "Consume all remaining argv tokens as TQL; command options must precede it."}}, Examples: []string{"ticket archive 20260913-00001", "ticket archive terminal", "ticket archive -q state:closed unclaimed", "ticket query terminal :: archive"}},
	{Name: "unarchive", Summary: "Return an archived ticket to the active repository.", Options: []Flag{{"ID (positional)", "id", "Full or unambiguous ticket ID."}}, Examples: []string{"ticket unarchive 20260913-00001"}},
	{Name: "bump", Summary: "Raise a ticket's priority or set it explicitly.", Options: []Flag{{"ID (positional)", "id", "Full or unambiguous shorthand ticket ID."}, {"-p, --priority", "int", "Set an exact priority from 0-4 instead of lowering it by one."}}, Examples: []string{"ticket bump 20260913-00001", "ticket bump 20260913-00001 --priority 1"}},
	{Name: "list", Summary: "List tickets (human default: all nonterminal; JSON default: open).", Options: []Flag{{"STATE... or ID... (positional)", "state|id|query", "Legacy states/IDs or shell-friendly TQL; -q/--query consumes the remaining TQL tokens."}, {"-q, --query", "TQL...", "Consume all remaining argv tokens as TQL; command options must precede it."}, {"-s, --state", "enum (repeatable)", "Select one or more ticket states."}, {"-a, --all", "bool", "Include closed/rejected and archived tickets."}, {"--archived", "bool", "List archived tickets only."}, {"-1, --ids", "bool", "Emit exactly one full ticket ID per line."}, {"--deps", "bool", "Show direct dependency status in human output or expanded JSON."}, {"-l, --long", "bool", "Accepted compatibility alias for the expanded list form."}, {"-t, --by-id", "bool", "Sort by descending ticket ID."}, {"-u, --by-modified", "bool", "Sort by most recently modified."}, {"--tag", "string (repeatable)", "All listed tags must be present."}, {"--without-tag", "string (repeatable)", "None of the listed tags may be present."}, {"--assignee", "token", "Exact assignee match."}, {"--unassigned", "bool", "No assignee."}, {"--parent", "id", "Exact parent match."}, {"--priority", "int", "Exact priority match."}, {"--limit", "int", "Positive result limit, default 20 unless bare human list or human all view is used."}, {"--offset", "int", "Skip this many sorted results before applying --limit."}, {"--fields", "csv", "Projection; id mandatory."}, {"--markdown", "bool", "Use Markdown table output."}, {"--graph", "bool", "Render the selected tickets as an induced dependency graph."}}, Examples: []string{"ticket list --tag billing --limit 50", "ticket list state:open ready", "ticket list id:202609", "ticket list id ge 202609", "ticket list -q state:open ready", "ticket list open hold", "ticket list 20260913-00001", "ticket list --state open --state hold", "ticket list -1 --state open", "ticket list --deps", "ticket ls -a", "ticket ls -l -t", "ticket ls -l -t -u", "ticket list --graph state:open"}},
	{Name: "query", Summary: "Select tickets with shell-friendly TQL and compose consumers.", Options: []Flag{{"TQL... (positional)", "query", "Field:value predicates, semantic predicates, and word operators."}, {"--all", "bool", "Include active and archived tickets."}, {"--archived", "bool", "Select archived tickets only."}, {"--sort", "enum", "priority-id, id-desc, or modified-desc; default priority-id."}, {"--offset", "int", "Skip matching tickets before applying the limit."}, {"--limit", "int", "Positive result limit; query default is unlimited."}, {"--fields", "csv", "Projection; id mandatory; with composition, use the list consumer after ::."}, {"--deps", "bool", "Show all direct dependency status; with composition, use the list consumer after ::."}, {"-1, --ids", "bool", "Emit exactly one full ticket ID per line; with composition, use the list consumer after ::."}, {"--markdown", "bool", "Use Markdown table output; with composition, use the list consumer after ::."}}, Examples: []string{"ticket query state:open ready", "ticket query id:202609", "ticket query id ge 202609", "ticket query not terminal", "ticket query tag:cleanup priority le P2", "ticket query --all archived state:closed", "ticket query state:open ready :: graph", "ticket query state:signoff :: close -m \"Accepted\"", "ticket query terminal id lt 202609 :: archive"}},
	{Name: "grep", Summary: "Find tickets by matching ID or complete TASK.md content.", Options: []Flag{{"EXPRESSION... (positional)", "string|regexp", "Every substring or regular expression must match ticket ID or content."}}, Examples: []string{"ticket grep parser", "ticket grep parser retry", "ticket grep '^20260913-'", "ticket grep '^# Fix'"}},
	{Name: "graph", Summary: "Explore dependency relationships as a readable tree or structured graph.", Options: []Flag{{"[ID|TQL...] (positional)", "id|query", "Optional ticket ID or shell-friendly TQL; omitted ID shows the active graph."}, {"-q, --query", "TQL...", "Consume all remaining argv tokens as TQL; command options must precede it."}, {"--reverse", "bool", "Traverse dependents instead of dependencies."}, {"--depth", "int", "Limit traversal depth from the selected root; unavailable for selected-set graphs."}, {"--all", "bool", "Include active and archived tickets."}, {"--archived", "bool", "Show archived tickets only."}, {"--ascii", "bool", "Force ASCII tree output."}, {"--unicode", "bool", "Force Unicode tree output."}}, Examples: []string{"ticket graph 20260922-00001", "ticket graph not terminal", "ticket graph -q state:open ready", "ticket query state:open ready :: graph", "ticket graph 20260922-00001 --reverse", "ticket graph --depth 2 --ascii", "ticket graph -j"}},
	{Name: "ready", Summary: "Inspect eligible work without claiming.", Options: []Flag{{"[open|review] (positional)", "queue", "Queue to inspect; open is the default and uses implementation readiness, while review lists unassigned review-eligible tickets."}, {"--tag", "string (repeatable)", "All listed tags must be present."}, {"--without-tag", "string (repeatable)", "None of the listed tags may be present."}, {"--parent", "id", "Exact parent match."}, {"--priority", "int", "Exact priority match."}, {"--limit", "int", "Positive result limit, default 20."}, {"--fields", "csv", "Projection; id mandatory."}, {"--markdown", "bool", "Use Markdown table output."}}, Examples: []string{"ticket ready", "ticket ready open", "ticket ready review"}},
	{Name: "next", Summary: "Select the first ticket from the open or review queue, optionally claiming it.", Options: []Flag{{"[open|review] (positional)", "queue", "Select implementation or review work; open is the default."}, {"--tag", "string (repeatable)", "Require every tag."}, {"--without-tag", "string (repeatable)", "Exclude tickets carrying any of these tags."}, {"--priority", "int", "Exact priority filter, 0-4."}, {"--claim", "bool", "Claim the selected ticket for --actor or TICKET_ACTOR."}, {"--markdown", "bool", "Use Markdown table output."}}, Examples: []string{"ticket next", "ticket next review --claim -j", "ticket next --tag backend --claim -j", "ticket next --without-tag no-review --claim -j"}},
	{Name: "wait", Summary: "Wait for open or review work, optionally claiming it.", Options: []Flag{{"[open|review] (positional)", "queue", "Select implementation or review work; open is the default."}, {"--tag", "string (repeatable)", "Require every tag."}, {"--priority", "int", "Exact priority filter, 0-4."}, {"--claim", "bool", "Resume this actor's matching work or claim available work."}}, Examples: []string{"ticket wait --claim -j", "ticket wait review --claim -j", "ticket wait --tag windows --claim -j"}},
	{Name: "watch", Summary: "Watch live ticket activity without changing repository state.", Options: []Flag{{"--actor", "token", "Filter to events attributed to an actor; - means unknown actor."}, {"--ticket", "id", "Filter to one exact ticket ID."}, {"--state", "enum", "Filter to the resulting ticket state."}, {"--tag", "string (repeatable)", "Require every listed tag."}, {"--without-tag", "string (repeatable)", "Exclude events whose ticket has any listed tag."}, {"--parent", "id", "Filter to one exact parent ID."}, {"--event", "string (repeatable)", "Filter to event kinds; repeated values are ORed."}}, Examples: []string{"ticket watch", "ticket watch --state review --event submitted", "ticket watch --tag backend --event claimed --event submitted", "ticket watch -j"}},
	{Name: "show", Summary: "Show one ticket (default sections: objective, acceptance, handoff, work log).", Options: []Flag{{"ID (positional)", "id", "Full or unambiguous shorthand ticket ID."}, {"--section", "key (repeatable)", "Known section key; replaces the default selection."}, {"--full", "bool", "Entire Markdown body after metadata."}, {"--max-bytes", "int", "Budget 1-1048576 for returned text."}, {"--readiness", "bool", "Include readiness and blocker computation."}, {"--markdown", "bool", "Use Markdown output."}}, Examples: []string{"ticket show", "ticket show 20260913-00001 --readiness", "ticket show 20260913-00001 --full"}},
	{Name: "edit", Summary: "Open a ticket in the configured editor.", Options: []Flag{{"ID (positional)", "id", "Full or unambiguous shorthand ticket ID."}}, Examples: []string{"ticket edit"}},
	{Name: "submit", Summary: "Submit an open ticket for independent review.", Options: []Flag{{"ID (positional)", "id", "Full or unambiguous shorthand ticket ID."}, {"--handoff", "string", "Replace Handoff text."}, {"-m, --message", "string", "Append an entry to Work log."}}, Examples: []string{"ticket submit -m \"Ready for review\"", "ticket submit 20260913-00001 -m \"Ready for review\" -j"}},
	{Name: "hold", Summary: "Put an open ticket on hold.", Options: []Flag{{"ID (positional)", "id", "Full or unambiguous shorthand ticket ID."}, {"--handoff", "string", "Replace Handoff text."}, {"-m, --message", "string", "Append an entry to Work log."}}, Examples: []string{"ticket hold 20260913-00001 -m \"Waiting for the API contract\""}},
	{Name: "review", Summary: "Send a ticket to review.", Options: []Flag{{"ID (positional)", "id", "Full or unambiguous shorthand ticket ID; omitted ID uses the current ticket."}, {"-m, --message", "string", "Append an entry to Work log."}}, Examples: []string{"ticket review 20260913-00001", "ticket review -m \"Ready for review\""}},
	{Name: "open", Summary: "Open a ticket for implementation.", Options: []Flag{{"[ID] [HANDOFF] (positional)", "id|string", "Optional ticket ID and positional Handoff text; omitted ID uses the current ticket."}, {"--handoff", "string", "Replace Handoff text."}, {"-m, --message", "string", "Append an entry to Work log."}, {"--claim", "bool", "Claim the opened ticket for --actor or TICKET_ACTOR."}}, Examples: []string{"ticket open 20260913-00001 -m \"Continue implementation\"", "ticket open 20260913-00001 --claim", "ticket open \"Continue implementation\""}},
	{Name: "state", Summary: "Force a lifecycle state.", Options: []Flag{{"ID STATE (positional)", "id state", "Full canonical ticket ID and one of the valid lifecycle states."}, {"-m, --message", "string", "Append an entry to Work log."}}, Examples: []string{"ticket state 20260913-00001 review", "ticket state 20260913-00001 rejected -m \"Administrative correction\""}},
	{Name: "status", Summary: "Show concise operational status for one ticket.", Options: []Flag{{"ID (positional)", "id", "Full or unambiguous shorthand ticket ID."}, {"--markdown", "bool", "Use Markdown output."}}, Examples: []string{"ticket status 20260913-00001", "ticket status 20260913-00001 -j"}},
	{Name: "path", Summary: "Resolve a ticket ID to its TASK.md path.", Options: []Flag{{"ID (positional)", "id", "Full or unambiguous shorthand ticket ID."}, {"--absolute", "bool", "Absolute filesystem path instead of ticket-root-relative."}}, Examples: []string{"ticket path 20260913-00001", "ticket path 20260913-00001 --absolute"}},
	{Name: "update", Summary: "Update fields and/or replace whole sections.", Options: []Flag{{"ID (positional)", "id", "Full or unambiguous shorthand ticket ID."}, {"-p, --priority", "int", "Set priority from 0-4."}, {"--tag", "string (repeatable)", "Replace tags; every tag must be unique."}, {"--input", "-", "Read a JSON object with set and/or sections from stdin."}}, Examples: []string{"ticket update 20260913-00001 --priority 1", "ticket update 20260913-00001 --tag windows --tag networking", "ticket update 20260913-00001 --input -"}},
	{Name: "append", Summary: "Append human Markdown to a ticket's Objective.", Options: []Flag{{"ID [OBJECTIVE_FILE|-] (positional)", "id|file", "Ticket ID and optional Objective source; - reads stdin."}, {"-o, --objective", "file", "Read Objective Markdown from a file or stdin with -."}}, Examples: []string{"ticket append 20260913-00001", "ticket append 20260913-00001 objective.md", "ticket append 20260913-00001 --objective -"}},
	{Name: "claim", Summary: "Claim an actionable unassigned ticket.", Options: []Flag{{"ID (positional)", "id", "Full or unambiguous shorthand ticket ID."}}, Examples: []string{"ticket claim 20260913-00001"}},
	{Name: "reassign", Summary: "Atomically transfer ticket ownership.", Options: []Flag{{"ID ASSIGNEE (positional)", "id|token", "Full or unambiguous ticket ID and target assignee."}, {"--handoff", "string", "Replace Handoff text."}, {"-m, --message", "string", "Append an entry to Work log."}, {"--input", "-", "Read a JSON object with assignee, handoff, and message fields from stdin."}}, Examples: []string{"ticket reassign 20260913-00001 reviewer", "ticket reassign 20260913-00001 --input -"}},
	{Name: "release", Summary: "Release ticket ownership.", Options: []Flag{{"ID (positional)", "id", "Full or unambiguous shorthand ticket ID."}, {"--handoff", "string", "Replace Handoff text."}, {"-m, --message", "string", "Append an entry to Work log."}, {"--input", "-", "Read a JSON object with release fields from stdin."}}, Examples: []string{"ticket release 20260913-00001"}},
	{Name: "close", Summary: "Close one or more tickets.", Options: []Flag{{"ID... or STATE... or TQL... (positional)", "id|state|query", "Ticket IDs, legacy states, or shell-friendly TQL; all, *, or -a closes every nonterminal ticket."}, {"-q, --query", "TQL...", "Consume all remaining argv tokens as TQL; command options must precede it."}, {"-s, --state", "state (repeatable)", "Select nonterminal tickets by state."}, {"--outcome", "string", "Optional outcome text."}, {"-m, --message", "string", "Append an entry to Work log."}, {"--input", "-", "Read a JSON object with optional outcome/message fields from stdin."}, {"-a, --all", "bool", "Close every nonterminal ticket."}}, Examples: []string{"ticket close", "ticket close state:signoff", "ticket close -q state:signoff tag:release", "ticket query state:signoff :: close -m \"Accepted\"", "ticket close 20260913-00001 -m \"Accepted after review\"", "ticket close open hold", "ticket close -s open -s review"}},
	{Name: "approve", Summary: "Approve review tickets for human signoff.", Options: []Flag{{"ID... or STATE... or TQL... (positional)", "id|state|query", "Review ticket IDs, legacy review selectors, or shell-friendly TQL."}, {"-q, --query", "TQL...", "Consume all remaining argv tokens as TQL; command options must precede it."}, {"-s, --state", "state (repeatable)", "Select review tickets by state; review is accepted."}, {"-m, --message", "string", "Append an entry to Work log."}}, Examples: []string{"ticket approve", "ticket approve state:review unclaimed", "ticket approve -q state:review tag:release", "ticket query state:review unclaimed :: approve", "ticket approve 20260913-00001 -m \"Reviewed and approved\"", "ticket approve review", "ticket approve all"}},
	{Name: "reject", Summary: "Reject a nonterminal ticket with an outcome.", Options: []Flag{{"[ID] [OUTCOME] (positional)", "id|string", "Optional ticket ID and rejection outcome; omitted ID uses the current ticket."}, {"--outcome", "string", "Nonempty rejection outcome (required unless supplied positionally)."}, {"-m, --message", "string", "Append an entry to Work log."}, {"--input", "-", "Read a JSON object with outcome/message fields from stdin."}}, Examples: []string{"ticket reject 20260913-00001 \"No longer needed\" -m \"Closing after review\"", "ticket reject \"No longer needed\""}},
	{Name: "check", Summary: "Validate ticket metadata and relationship graphs.", Options: []Flag{{"--active", "bool", "Validate active tickets only; referenced archived tickets still resolve."}}, Examples: []string{"ticket check", "ticket check --active", "ticket check --active -j"}},
	{Name: "actor", Summary: "Show the effective actor identity.", Examples: []string{"ticket actor", "ticket actor -j"}},
	{Name: "info", Summary: "Show selected repository metadata.", Examples: []string{"ticket info", "ticket info -j"}},
	{Name: "version", Summary: "Report version, API version, and storage version.", Examples: []string{"ticket version"}},
	{Name: "help", Summary: "Show help for one command, or list commands.", Options: []Flag{{"COMMAND (positional)", "command", "Command to describe."}}, Examples: []string{"ticket help", "ticket help create"}},
}
